const catalogData = {
  items: [
    { title: "FOYER", drawing: "drawings/axo/foyer.jpg" },
    { title: "KINO", drawing: "drawings/axo/kino.jpg" },
    { title: "SAL", drawing: "drawings/axo/sal.jpg" },
    { title: "PONORKA", drawing: "drawings/axo/ponorka.jpg" },
    { title: "N01", model: "models/zidle_01/zidle_01.gltf" },
    { title: "N02", model: "models/zidle_02/zidle_02.gltf" },
    { title: "N03", model: "models/zidle_03/zidle_03.gltf" },
    { title: "N04", model: "models/kreslo_02/kreslo_02.gltf" },
    { title: "N05", model: "models/kreslo_01/kreslo_01.gltf" },
    { title: "N06", model: "models/kreslo_03/kreslo_03.gltf" },
    { title: "N07", model: "models/kreslo_04/kreslo_04.gltf" },
    { title: "N08", model: "models/stul_01/stul_01.gltf" },
    { title: "N09", model: "models/stul_02/stul_02.gltf" },
    { title: "N10", model: "models/stul_03/stul_03.gltf" },
    { title: "N11", model: "models/stul_04/stul_04.gltf" },
    { title: "N12", model: "models/stul_05/stul_05.gltf" },
    { title: "N13", model: "models/stul_06/stul_06.gltf" },
    { title: "I01", model: "models/lampa_01/lampa_01.gltf" },
    { title: "I02", model: "models/lampa_02/lampa_02.gltf" },
    { title: "I03", model: "models/svetlo_02/svetlo_02.gltf" },
    { title: "I04", model: "models/svetlo_01/svetlo_01.gltf" },
    { title: "I05", model: "models/panel_01/panel_01.gltf" },
    { title: "U01", drawing: "drawings/keramika/ker_pudorys.jpg", drawing_alt: "drawings/keramika/ker_vzory.jpg" },
    { title: "U02", drawing: "drawings/mozaika/mozaika_detail.jpg", drawing_alt: "drawings/mozaika/mozaika.jpg"},
    { title: "U03", drawing: "drawings/libbry/libensky_brychtova.jpg"},
    { title: "U04", drawing: "drawings/lustr/lustr_modry.jpg", drawing_alt: "drawings/lustr/lustr_zluty.jpg" },
    { title: "U05", drawing: "drawings/tapiserie/tapiserie_modra.jpg"},
    { title: "U06", drawing: "drawings/janosik/tapiserie_janosik.jpg"},
    { title: "U07", drawing: "drawings/stredovek/tisk_stredovek_01.jpg", drawing_alt: "drawings/stredovek/tisk_stredovek_02.jpg" },
    { title: "U08", drawing: "drawings/kone/kone.jpg" },
  ]
};
